server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    password: root123
    username: root  
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: HOTEL-SERVICE     
        
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      timeZone: http://localhost:8761/eureka
    
